# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Rosen's Portfolio
tagline:          'A Jekyll theme'
description:      'desc'
url:              https://rosen369.github.io/
baseurl:          /

author:
  name:           'Rosen Jiao'
  url:            https://rosen369.github.io/

paginate:         5

github:
  repo:           https://github.com/Rosen369/Rosen369.github.io
