# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'desc'
url:              https://rosen369.github.io/
baseurl:          /

author:
  name:           'Rosen Jiao'
  url:            https://rosen369.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
