# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Rosen
tagline:          'Collections'
description:      'Programmer'
baseurl:          https://rosen369.github.io/

author:
  name:           'Rosen Jiao'

paginate:         5

github:
  repo:           https://github.com/Rosen369/Rosen369.github.io